-- Completion Plugin Setup
local cmp = require('cmp')
cmp.setup({
    -- Enable LSP snippets
    snippet = {
        expand = function(args)
            vim.fn["UltiSnips#Anon"](args.body)
        end,
    },
    mapping = {
            ['<C-p>'] = cmp.mapping.select_prev_item(),
            ['<C-n>'] = cmp.mapping.select_next_item(),
        -- Add tab support
            ['<S-Tab>'] = cmp.mapping.select_prev_item(),
            ['<Tab>'] = cmp.mapping.select_next_item(),
            ['<C-S-f>'] = cmp.mapping.scroll_docs(-4),
            ['<C-f>'] = cmp.mapping.scroll_docs(4),
            ['<C-Space>'] = cmp.mapping.complete(),
            ['<C-e>'] = cmp.mapping.close(),
            ['<CR>'] = cmp.mapping.confirm({
            behavior = cmp.ConfirmBehavior.Insert,
            select = true,
        })
    },
    -- Installed sources:
    sources = {
        { name = 'path' },                                       -- file paths
        { name = 'nvim_lsp',               keyword_length = 3 }, -- from language server
        { name = 'nvim_lsp_signature_help' },                    -- display function signatures with current parameter emphasized
        { name = 'nvim_lua',               keyword_length = 2 }, -- complete neovim's Lua runtime API such vim.lsp.*
        { name = 'buffer',                 keyword_length = 2 }, -- source current buffer
        { name = 'ultisnips',              keyword_length = 2 }, 
        { name = 'calc' },                                       -- source for math calculation
    },
    window = {
        completion = cmp.config.window.bordered(),
        documentation = cmp.config.window.bordered(),
    },
    formatting = {
        fields = { 'menu', 'abbr', 'kind' },
        format = function(entry, item)
            local menu_icon = {
                nvim_lsp = 'λ',
                vsnip = '⋗',
                buffer = 'Ω',
                path = '🖫',
            }
            item.menu = menu_icon[entry.source.name]
            return item
        end,
    },
})


-- Treesitter Plugin Setup
require('nvim-treesitter.configs').setup {
    ensure_installed = { "bash", "c", "cmake", "css", "go", "gomod", "gowork", "hcl", "html",
        "http", "javascript", "json", "make", "markdown", "python", "regex", "ruby", "rust", "toml", "vim",
        "yaml",
         "proto", },
    auto_install = true,
    ignore_install = { "latex" },
    highlight = {
        enable = true,
    },
    incremental_selection = {
        enable = true,
        keymaps = {
            init_selection = "<S-Tab>",  -- normal mode
            node_incremental = "<Tab>",  -- visual mode
            node_decremental = "<S-Tab", -- visual mode
        },
    },
    ident = { enable = true },
    rainbow = {
        enable = true,
    }
}

-- gopls
--require('lspconfig').gopls.setup {}

-- Telescope Setup
require('telescope').setup {
    defaults = {
        file_ignore_patterns = {
            "^./.git/",
            "^./target/",
            "LICENSE*"
        },
        layout_strategy = 'vertical',
        layout_config = { height = 0.95, width = 0.95 },
        mappings = {
            i = {
                ["<C-j>"] = require('telescope.actions').move_selection_next,
                ["<C-k>"] = require('telescope.actions').move_selection_previous,
            },
            n = {
                ["<C-j>"] = require('telescope.actions').move_selection_next,
                ["<C-k>"] = require('telescope.actions').move_selection_previous,
            }
        },
    },
    pickers = {
        lsp_workspace_symbols = {
            symbol_width = 50,
            symbol_type_width = 12,
            show_line = true,
        },
        lsp_document_symbols = {
            symbol_width = 50,
            symbol_type_width = 12,
            show_line = true,
        },
    },
    extensions = {
        --media_files = {
        -- filetypes whitelist
        -- defaults to {"png", "jpg", "mp4", "webm", "pdf"}
        --  filetypes = { "png", "webp", "jpg", "jpeg", "ppm", "pdf" },
        --find_cmd = "rg", -- find command (defaults to `fd`)
        -- },
    },
}

-- Nvim Tree Setup
-- we want to run costim filters in nvim tree for latex projects
-- because we dont want to be indexing over the general latex
-- cruft generated by the autocompilation processes
local function is_latex_project()
    local files = vim.fn.glob("*.tex", false, true)
    return #files > 0
end

local function get_custom_filters()
    if is_latex_project() then
        return {
            "*.aux", "*.log", "*.pdf", "*.gz",
            "*.fdb_latexmk", "*.fls", "*.bbl", "*.blg"
        }
    else
        return {}
    end
end


require('nvim-tree').setup {

    sort_by = "case_sensitive",
    view = {
        adaptive_size = false,
    },
    renderer = {
        group_empty = true,
        icons = {
            git_placement = "after",
            glyphs = {
                git = {
                    unstaged = "-",
                    staged = "s",
                    untracked = "u",
                    renamed = "r",
                    deleted = "d",
                    ignored = "i",
                },
            },
        },
    },
    filters = {
        dotfiles = false,
        custom = get_custom_filters()
    },
    git = {
        ignore = false,
    },
}

require("ibl").setup {
    -- For indent-blankline v3+ (latest version)
    indent = {
        char = "│", -- Choose the character you prefer for indent lines
        tab_char = "│",
    },
    scope = { 
        enabled = true,
        show_start = true,
        show_end = false,
        highlight = {"Function", "Label"},
    },
    exclude = {
        filetypes = {
            "help",
            "dashboard",
            "NvimTree",
            "Trouble",
            "lazy",
            "mason",
            "notify",
            "toggleterm",
        },
        buftypes = {
            "terminal",
            "nofile",
            "quickfix",
            "prompt",
        },
    },
}
